### ISSUE TITLE
.query undefined

### ISSUE THREAD

**Issue by granteagon** [balderdashy/sails-postgresql#192]
In sails console, I should be able to:
```js
User.query("SELECT * FROM USER")
```
But I get undefined is not a function, meaning .query is undefined.

I've reinstalled/updated sails, waterline and sails-postgresql, as well as sails globally and I still get the same error.

Thanks!

**Comment by particlebanana** [comment]
Hmm are you sure everything is configured to use sails-postgresql? The `.query` method isn't available in sails-disk which is the default adapter in a sails project.

**Comment by granteagon** [comment]
Just figured it out.  I was using the key `adapter` instead of `module` in config/connections.js.  Sails docs specify adapter for some reason.

**Comment by loulin** [comment]
I got the same error. The reason is that this function must have a callback. See [doc](https://github.com/balderdashy/waterline-docs/blob/master/queries/query-methods.md#query-query-data-callback-)
But I think it should throw a more clear error: [L128](https://github.com/balderdashy/sails-postgresql/blob/master/lib/adapter.js#L128), and also the callback is not always needed.
